apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.x # On fixe une version stable
    helm:
      values: |
        grafana:
          adminPassword: "admin"  # Pour simplifier le lab (en prod on utilise des Secrets)
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # ArgoCD va créer le dossier "monitoring"
      - ServerSideApply=true #On dit a argocd de laisser k8s faire les calculs
